### ISSUE TITLE
Add "buyable" category

### ISSUE THREAD

**Issue by balidani** [balidani/emoji#13]
Add a category for symbols that can be bought in the shop.

**Comment by dave-gray101** [comment]
Since it's more likely than not that most items are buyable... might it be better to invert this and have a category for "unbuyable"?

**Comment by balidani** [comment]
Fixed by @dave-gray101 in https://github.com/balidani/emoji/commit/4598e71f67e7b88162aad1f32791b0b89cc6f50d
